version: '3.5'
services:
  web:
    image: peerapolbew/odoo:12.0
    restart: always
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./odoo-log-data:/var/log/odoo

volumes:
  odoo-web-data:
