{
    'name': "BiOne Stock Picking From Invoice",
    'version': '12.0.1.1.1',
    'summary': """Stock Picking From Customer/Supplier Invoice""",
    'description': """This Module Enables To Create Stocks Picking From Customer/Supplier Invoice""",
    'author': "Bi One Solutions",
    'company': 'Bi One Solutions',
    'website': "https://www.thaiodoo.com",
    'category': 'Accounting',
    'depends': ['base', 'account', 'stock'],
    'data': ['views/invoice_stock_move_view.xml'],
    'images': ['static/description/banner.jpg'],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
