
{
    'name': 'SARABAN Addons',
    'version': '12.0.1',
    'website': '',
    'license': '',
    'author': "Zephyr",
    'category': 'Localisation/Asia',
    'description': "SARABAN Addons",
    'depends': [
        'base',
        'hr',
        'mail',
        'pfb_saraban',
        'web',
    ],
    'data': [
        # 'security/group_saraban.xml',
        # 'views/document_main.xml',
        # #  'views/session_board.xml',
        'views/hr.xml',
        # 'views/sequence.xml',
        'views/setting.xml',
        'views/internal_document.xml',
        # 'wizard/wiz_send_email_view.xml',
        # 'views/internal_document_announce.xml',
        'views/receive.xml',
        'views/employee_groups_view.xml',

        'views/receive_external_report.xml',
        'views/internal_document_export.xml',
        'views/internal_document_main_report.xml',
        'views/internal_document_all_report.xml',
        'views/menuitem.xml',
        # 'views/action_button.xml',
        'wizard/make_approval_wizard_view.xml',
        'wizard/make_approval_wizard_view_receive.xml',
        # 'wizard_word/word_wizard_wizard_view.xml',
        'data/order_choices_data.xml',
        # 'data/mail.xml',
        # 'data/email_template_data.xml',
        'security/ir.model.access.csv',
        'security/group_saraban.xml'
    ],
    'installable': True,
    'application': True,
}

