{
    'name': ' Fin System Inherit ',
    'version': '12.0.1.0.1',
    'author': 'PP',
    'license': 'AGPL-3',
    'website': '',
    'category': 'Fields',
    'depends': ['base',
                'web',
                'mail',
                'fin_system',
                'fin_system_extension',
                'purchase_request',
                ],
    'data': [
        'security/ir.model.access.csv',
        'views/security.xml',
        'views/fin_system_100.xml',
        'views/fin_system_201.xml',
        'views/fin_system_401.xml',
        'views/account_analytic.xml',
        'views/purchase_request.xml',
    ],
    'installable': True,
}
